# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


DEPARTMENTS = [
    "ASPSU - Student Affairs",
    "Academic & Research Computing - Office of Information Technology",
    "Academic Affairs",
    "Advising & Career Services",
    "Alumni Relations - University Advancement",
    "Anthropology - Liberal Arts & Sciences",
    "Applied Linguistics - Liberal Arts & Sciences",
    "Architecture, College of the Arts",
    "Art + Design, College of the Arts",
    "Athletics",
    "Auxiliary Services",
    "Biology - Liberal Arts & Sciences",
    "Black Studies - Liberal Arts & Sciences",
    "Box Office - Auxiliary Services",
    "Budget",
    "Business Accelerator",
    "Business Accounting Services - Finance and Accounting Services Team",
    "Business Administration, School of",
    "Business Intelligence - Office of Information Technology",
    "CIO Office - Office of Information Technology",
    "Campus Accounting Services - University Financial Services",
    "Campus Planning Office",
    "Campus Rec - Student Affairs",
    "Campus Sustainability Office",
    "Capital Projects & Construction",
    "Center for Academic Excellence - Academic Affairs",
    "Center for Executive and Professional Education, Crown Plaza",
    "Center for Public Health Studies - Urban & Public Affairs",
    "Center for Public Service - School of Government",
    "Challenge - Liberal Arts & Sciences",
    "Chemistry - Liberal Arts & Sciences",
    "Chicano/Latino Studies - Liberal Arts & Sciences",
    "Child Welfare Partnership - Graduate School of Social Work, Salem Center",
    "Child and Family Studies - Graduate School of Social Work",
    "Children's Center - Education",
    "Civil & Environmental Engineering - Engineering & Computer Science, Maseeh College of",
    "College of Urban & Public Affairs - Deans Office",
    "College of Urban and Public Affairs",
    "College of the Arts",
    "Communication - Liberal Arts & Sciences",
    "Community Health - Urban & Public Affairs",
    "Computer Action Team - Engineering & Computer Science, Maseeh College of",
    "Computer Science - Engineering & Computer Science, Maseeh College of",
    "Computing Infrastructure Services - Office of Information Technology",
    "Conferences & Events - Auxiliary Services",
    "Conflict Resolution - Liberal Arts & Sciences",
    "Contracting and Procurement Services - University Financial Services",
    "Counseling & Psychological Services - Student Affairs",
    "Counselor Eduction - Graduate School of Education",
    "Criminology and Criminal Justice - Urban & Public Affairs",
    "Curriculum & Instruction - Graduate School of Education",
    "Dean of Student Life - Student Affairs",
    "Departmental Research Support Services - Liberal Arts & Sciences",
    "Disability Resource Center - Student Affairs",
    "Diversity and Multicultural Student Services - Student Affairs",
    "Diversity and Multicultural Student Services - Student Support Services - TRIO",
    "Early Childhood Training Center - Graduate School of Education",
    "Economics - Liberal Arts & Sciences",
    "Education Abroad - International Affairs",
    "Education, Graduate School of",
    "Educational Leadership and Policy - Graduate School of Education",
    "Electrical & Computer Engineering - Engineering & Computer Science, Maseeh College of",
    "Engineering & Computer Science, Maseeh College of",
    "Engineering & Technology Management - Engineering & Computer Science, Maseeh College of",
    "English - Liberal Arts & Sciences",
    "Enrollment Management and Student Affairs",
    "Enrollment Management and Student Affairs IT - Enrollment Management and Student Affairs",
    "Enterprise Solutions - Office of Information Technology",
    "Environmental Biology - Liberal Arts & Sciences",
    "Environmental Health & Safety",
    "Environmental Sciences and Management - Liberal Arts & Sciences",
    "Executive Leadership Institute - Urban & Public Affairs",
    "Facilities & Property Management",
    "Fariborz Maseeh Mathematics and Statistics - Liberal Arts & Sciences",
    "Finance & Administration",
    "First Stop Portland",
    "Food Market Business Development Institute - Business Administration",
    "Foundation",
    "Geography - Liberal Arts & Sciences",
    "Geology - Liberal Arts & Sciences",
    "Global Diversity & Inclusion - Presidents Office",
    "Government Relations",
    "Graduate Studies, Office of - Academic Affairs",
    "Helen Gordon Child Development Center - Education",
    "History - Liberal Arts & Sciences",
    "Human Resources",
    "Institute for Natural Resources - Liberal Arts & Sciences",
    "Institute for Sustainable Solutions",
    "Institute of Portland Metropolitan Studies - Urban & Public Affairs",
    "Institute on Aging - Urban & Public Affairs",
    "Institutional Research & Planning - Presidents Office",
    "Instructional Technology Services - Office of Information Technology",
    "Intensive English Language Program",
    "International Affairs",
    "International Studies - Liberal Arts & Sciences",
    "Judaic Studies - Liberal Arts & Sciences",
    "Liberal Arts & Sciences, College of",
    "Library",
    "MESA - Engineering & Computer Science, Maseeh College of",
    "Material Management Services",
    "Mechanical & Materials Engineering - Engineering & Computer Science, Maseeh College of",
    "Military Science - Academic Affairs",
    "Multicultural Center - Student Affairs",
    "Music, College of the Arts",
    "National Policy Consensus Center - Liberal Arts & Sciences",
    "Native American Studies - Liberal Arts & Sciences",
    "Non-Credit Solutions - University Financial Services",
    "Office of Academic Innovation",
    "Office of Admissions & New Student Programs - Enrollment Management & Student Affairs",
    "Office of Alumni Relations",
    "Office of Information Technology",
    "Office of International Admissions & Ed Partnerships - Enrollment Management & Student Affairs",
    "Office of the Registrar - Enrollment Management & Student Affairs",
    "Oregon Center for Advanced Technology - Engineering & Computer Science, Maseeh College of",
    "Oregon Center for Career Development in Childhood Care & Education - Graduate School of Education",
    "Oregon Institute of Technology",
    "Oregon Transportation Research and Education Consortium",
    "Philosophy - Liberal Arts & Sciences",
    "Physics - Liberal Arts & Sciences",
    "Political Science - Urban & Public Affairs",
    "Population Research - Urban & Public Affairs",
    "Presidents Office",
    "Property and Risk Management Department",
    "Psychology - Liberal Arts & Sciences",
    "Public Access Services - Library",
    "Public Administration - Urban & Public Affairs",
    "Public Safety",
    "Publications - University Relations",
    "Queer Resource Center - Student Affairs",
    "Regional Research Institute - Social Work",
    "Religious Studies - Liberal Arts & Sciences",
    "Research & Strategic Partnerships (RSP)",
    "Resource Services - Library",
    "School of Government - Urban & Public Affairs",
    "School of the Environment - Liberal Arts & Sciences",
    "Science Ed Center - Liberal Arts & Sciences",
    "Smith Memorial Student Union - Auxiliary Services",
    "Social Work, School of",
    "Sociology - Liberal Arts & Sciences",
    "Special Education - Graduate School of Education",
    "Speech and Hearing Sciences - Liberal Arts & Sciences",
    "Sponsored Projects Administration - Research & Strategic Partnerships",
    "Stott Center, Peter W - Athletics",
    "Student Activities and Leadership - Student Affairs",
    "Student Affairs",
    "Student Financial Aid and Scholarships",
    "Student Financial Services, A/R - University Financial Services",
    "Student Financial Services, E-Commerce - University Financial Services",
    "Student Health and Counseling - Student Affairs",
    "Student Legal Services - Student Affairs",
    "Student Services - Business Administration",
    "Summer Housing and Conferencing - Auxiliary Services",
    "Survey Research Lab - Research & Strategic Partnerships (RSP)",
    "Systems Science - Liberal Arts & Sciences",
    "Technology Support & Reporting Services - University Financial Services",
    "Telecomm Systems  - Office of Information Technology",
    "Testing Services - Student Health and Counseling - Student Affairs",
    "The Learning Center",
    "Theatre & Film, College of the Arts",
    "Transportation and Parking Services",
    "University Advancement",
    "University Communications - Presidents Office",
    "University Financial Services",
    "University General Counsel",
    "University Honors",
    "University Housing and Residence Life",
    "University Market - Auxiliary Services",
    "University Place - Auxiliary Services",
    "University Relations",
    "University Studies - Academic Affairs",
    "Urban & Public Affairs, College of",
    "Urban Studies & Planning - Urban & Public Affairs",
    "User Support Services - Office of Information Technology",
    "Vanguard",
    "Vice President for Enrollment and Student Affairs",
    "Women, Gender, and Sexuality Studies - Liberal Arts & Sciences",
    "Womens Resource Center - Student Affairs",
    "World Languages and Literatures - Liberal Arts & Sciences",
]

BUILDINGS = [
    ("AB", "Art Building"),
    ("ASRC", "Academic and Student Recreation Center"),
    ("BA", "School of Business Administration"),
    ("BBG", "Blumel Bike Garage"),
    ("BHB", "Broadway Residence Hall"),
    ("BLKS", "Blackstone Residence Hall"),
    ("JCB", "Joseph C. Blumel Residence Hall"),
    ("COR", "Corbett Building"),
    ("CLKCC", "Clackamas Community College"),
    ("CAP", "Capital Center High School"),
    ("GORGE", "Columbia Gorge CC"),
    ("CGT", "Campus and Grounds Trailer"),
    ("CH", "Cramer Hall"),
    ("CLSB", "Collaborative Life Sciences Building"),
    ("CPB", "Crown Plaza Building"),
    ("EB", "Engineering Building"),
    ("ED", "School of Education"),
    ("EH", "East Hall"),
    ("SEH", "Stephen E. Epler Residence Hall"),
    ("FAB", "Fourth Avenue Building"),
    ("CIN", "Fifth Avenue Cinema"),
    ("FAL", "Fifth Avenue Lot"),
    ("HOFF", "George C. Hoffmann Hall"),
    ("HGCDC", "Helen Gordon Child Development Center"),
    ("HH", "Harder House"),
    ("HSB", "Harrison Street Building"),
    ("KNGA", "King Albert Residence Hall"),
    ("KHSE", "Koinonia House"),
    ("LH", "Lincoln Hall"),
    ("NASCC", "Native American Student and Community Center"),
    ("METRO", "Metro Center"),
    ("MCB", "Market Center Building"),
    ("MONT", "Montgomery Residence Hall"),
    ("MHCC", "Mount Hood Community College"),
    ("ML", "Branford Price Millar Library "),
    ("MSQ", "Market Square Building"),
    ("NGH", "North Greenhouse"),
    ("NH", "Neuberger Hall"),
    ("OCATE", "Oregon Center for Advanced Technology Education"),
    ("OGI", "Oregon Grad Institute Science & Engineering "),
    ("OND", "Ondine Residence Hall"),
    ("PKWY", "Parkway Residence Hall"),
    ("PCC-CA", "PCC Cascade Campus"),
    ("PCC-RC", "PCC Rock Creek Campus"),
    ("PS1", "Parking Structure One"),
    ("PS2", "Parking Structure Two"),
    ("PS3", "Parking Structure Three"),
    ("RGH", "Research Greenhouse"),
    ("SB1", "Science Building One"),
    ("SBH", "Simon Benson House"),
    ("STFR", "Stratford Residence Hall"),
    ("PSC", "Peter W. Stott Center"),
    ("SEC", "Science and Education Center"),
    ("PSCF", "Peter W. Stott Community Field"),
    ("SGH", "South Greenhouse"),
    ("STHL", "Saint Helens Residence Hall"),
    ("SH", "Shattuck Hall"),
    ("SMSU", "Smith Memorial Student Union"),
    ("SRTC", "Science Research and Teaching Center"),
    ("URBN", "Urban Center Building"),
    ("UCB", "University Center Building"),
    ("UHP", "University Honors Program"),
    ("UOP", "University of Portland"),
    ("UP", "University Place"),
    ("PNT", "University Pointe at College Station"),
    ("USB", "University Services Building"),
    ("UTS", "University Technology Services"),
    ("WCC", "Willow Creek Center"),
    ("WHP", "West Heating Plant"),
    ("XSB", "Extended Studies Building"),
]

MAILCODES = [
    ("AAUP", "American Association of University Professors, 232 SMSU"),
    ("ACS", "Advising & Career Services, 402 USB"),
    ("ADM", "Admissions Office, 104 NH"),
    ("AITP", "American Indian Urban Teacher Program, 239 XSB"),
    ("ALUM", "Alumni Relations, 1 SBH"),
    ("ANTH", "Anthropology Department, 141 CH"),
    ("ARA", "Aramark, 114 SMSU"),
    ("ARCH", "Architecture, School of, 235 SH"),
    ("ART", "Art + Design, School of, 310 AB"),
    ("ASIA", "Institute for Asian Studies, 308 EH"),
    ("ASPSU", "Associated Students, PSU, 117 SMSU"),
    ("ATH", "Athletics, 415 UCB"),
    ("AUXS", "Auxiliary Services, 207 OND"),
    ("AV", "Audio Visual Services, 18 SMSU"),
    ("BIO", "Biology Department, 246 SRTC"),
    ("BOOK", "Portland State Bookstore, 1715 SW 5th"),
    ("BOX", "Box Office, 120 SMSU"),
    ("BST", "Black Studies Department, 150 XS"),
    ("BUD", "Budget Office, 515 MCB"),
    ("CAPS", "Counseling & Psychological Services, 200 UCB"),
    ("CAPS-TESTING", "Testing Service, 310 UCB"),
    ("CCC", "Child Care Center, ASPSU, 126 SMSU"),
    ("CDC", "Helen Gordon Child Development Center, 1 Helen Gordon"),
    ("CEE", "Civil and Environmental Engineering Department, 200 EB"),
    ("CEED", "Continuing Education, School of Education, 204 ED"),
    ("CENS", "Oregon State Data Center, 233 UPA"),
    ("CFS", "Child and Family Services, 200 Helen Gordon"),
    ("CHAN", "Chancellors Office, 530 URBN"),
    ("CHEM", "Chemistry Department, 262 SRTC"),
    ("CHNW", "College Housing Northwest, 111 Montgomery"),
    ("CLAS", "Liberal Arts & Sciences, College of, 341 CH"),
    ("CLS", "Chicano-Latino Studies, 150 XS"),
    ("CMPS", "Computer Science, 120 FAB"),
    ("COR", "Corbett Building"),
    ("COTA", "College of the Arts, 349 LH"),
    ("CPC", "Capital Projects & Construction, 302 USB"),
    ("CPO", "Campus Planning Office, 340 MCB"),
    ("CPSO", "Campus Public Safety, 100 CPSO"),
    ("CR", "Conflict Resolution, 239 NH"),
    ("CREC", "Campus Recreation, 210 ASRC"),
    ("CSE", "Center for Science Education, 101 SEH"),
    ("CSO", "Campus Sustainability Office, 128 MCB"),
    ("CTS", "Center for Transportation Studies, 350 URBN"),
    ("CUS", "Center for Urban Studies, 350 URBN"),
    ("CWP", "Child Welfare Partnership, 400 UCB"),
    ("DEV", "Development, Office of, 730 MCB"),
    ("DMSS", "Diversity and Multicultural Student Services, 425 SMSU"),
    ("DOS", "Dean of Students, Office of, 433 SMSU"),
    ("DRC", "Disability Resource Center, 116 SMSU"),
    ("DRSS", "Departmental Research Support Services, 27-41 NH"),
    ("ECE", "Electrical and Computer Engineering Department, 160 FAB"),
    ("ECON", "Economics Department, 241 CH"),
    ("ECTC", "Early Childhood Training Center, 204 ED"),
    ("ED", "Education, School of, 602 ED"),
    ("ED-MEDIA LAB", "Educational Media Laboratory, 310 ED"),
    ("EHS", "Environmental Health & Safety, 202 USB"),
    ("EMSA", "Enrollment Management & Student Affairs, 345 CH"),
    ("EMSAIT", "EMSA IT, 351 CH"),
    ("ENG", "English Department, 405 NH"),
    ("EOP", "Educational Opportunity Program, 458 SMSU"),
    ("ESM", "School of the Environment, 118 SRTC"),
    ("ESM", "Environmental Sciences & Management Doctoral Program, 218 SRTC"),
    ("ETM", "Engineering and Technology Management Program, LL50 FAB"),
    ("ETS", "Educational Talent Search, 100 KHSE"),
    ("FA", "Financial Aid, Student, 176 NH"),
    ("FADM", "Finance & Administration Office, 515 MCB"),
    ("FAST", "University Financial Services Directors Office, 260 MCB"),
    ("FAST-BAS", "Business Accounting Services, 260 MCB"),
    ("FAST-BSC", "Management Office, BSC, 260 MCB"),
    ("FAST-CAPS", "Contracting and Procurement Services, 260 MCB"),
    ("FAST-CAS", "Campus Accounting Services, 260 MCB"),
    ("FAST-DBS", "Department Budget Services, 260 MCB"),
    ("FAST-STORES", "Materials Management - Stores, 1 USB"),
    ("FAST-TSRS", "Technology Support and Reporting Services, 260 MCB"),
    ("FAST-UM", "Utilities Management, 260 MCB"),
    ("FOUND", "Foundation Office, S510 UTS"),
    ("FPM", "Facilities & Property Management, 202 USB"),
    ("GDI", "Global Diversity & Inclusion, 830 MCB"),
    ("GEOG", "Geography Department, 424 CH"),
    ("GEOL", "Geology Department, 17 CH"),
    ("GOLD", "Reserve Officers Training Corps, 204 UTS"),
    ("HON", "Honors Program, University, 103 UHP"),
    ("HRC", "Human Resources, 518 MCB"),
    ("HST", "History Department, 441 CH"),
    ("IELP", "Intensive English Language Program, 400 UCB"),
    ("IES", "Fulbright Adviser, 101 EH"),
    ("IES-ISFS", "International Student & Faculty Services, 212 EH"),
    ("INR", "Institute for Natural Resources, 140 SEC"),
    ("INTL", "International Studies Program, 101 EH"),
    ("IOA", "Institute on Aging, 470 URBN"),
    ("IPMS", "Institute of Portland Metropolitan Studies, 780 URBN"),
    ("JST", "Judaic Studies, 465 UCB"),
    ("JUST", "Criminology and Criminal Justice, Division of, 550 URBN"),
    ("LIBW", "Library, Millar, 110 ML"),
    ("LING", "Applied Linguistics Department, UCB 335"),
    ("LLTR", "Literacy, Language & Technology Research Group, V300 UCB"),
    ("LS", "Student Legal Services, M340 SMSU"),
    ("MAIL", "Mail Services, 114 USB"),
    ("MCC", "Multicultural Center, 230 SMSU"),
    ("MCECS", "Maseeh College of Engineering and Computer Science, 500 EB"),
    ("MESA", "Mathematics, Engineering & Science Achievement, 104 EB"),
    ("MESC", "Middle East Studies Center, 322 EH"),
    ("MME", "Mechanical and Materials Engineering Department, 400 EB"),
    ("MMS", "Materials Management Services, 114 USB"),
    ("MMS-STORE", "Material Management Services, Facilities, 114 USB"),
    ("MTH", "Fariborz Maseeh Mathematics and Statistics Department, 334 NH"),
    ("MUS", "Music, School of, 231 LH"),
    ("NAC", "Native American Center, 100 NACSC"),
    ("NBS", "Norris, Beggs, and Simpson, 308 UCB"),
    ("NPCC", "National Policy Consensus Center, 720 URBN"),
    ("OAA", "Academic Affairs, Office of, 650 MCB"),
    ("OAI", "Office of Academic Innovation, 209M, SMSU"),
    ("OCCD", "Oregon Center for Career Development in Childhood Care and Education, 101 SAB"),
    ("OCSC", "Oregon Community Service Commission, 210 KHSE"),
    ("OGS", "Graduate Studies, Office of, 184 XSB"),
    ("OIA", "International Affairs, 101 EH"),
    ("OIRP", "Institutional Research & Planning, M343 SMSU"),
    ("OIT-COMP", "EITS, 600 UTS"),
    ("OIT-DO", "Directors Office, 634 UTS"),
    ("OIT-USS", "User Support Services, 18 SMSU"),
    ("ORCC", "Oregon Campus Compact, 210 KHSE"),
    ("ORN", "New Student Orientation, 131 NH"),
    ("OTREC", "Oregon Transportation Research and Education Consortium, 301V EB"),
    ("OVA", "Veterans Services, 425 SMSU"),
    ("PA", "Public Administration, Division of, 650 URBN"),
    ("PERSIA", "Persia House, M312 SMSU"),
    ("PHE", "Athletic Training Program, 143 PSC"),
    ("PHIL", "Philosophy Department, 471 NH"),
    ("PHR", "Pacific Historical Review, 487 CH"),
    ("PHY", "Physics Department, 134 SRTC"),
    ("PO", "Presidents Office, 850 MCB"),
    ("PRC", "Population Research Center, 570 URBN"),
    ("PRM", "Property and Risk Management Department, FPM"),
    ("PS", "Political Science, Division of, 650 URBN"),
    ("PSC", "Peter Stott Center, 212 PSC"),
    ("PSY", "Psychology Department, 317 CH"),
    ("RAPS", "Retired-Emeriti Professors of Portland State, 201 SBH"),
    ("RES", "Residence Life, 230 BHB"),
    ("RO", "Registration & Records, 104 NH"),
    ("RRI", "Regional Research Institute for Human Services, 900 ATT"),
    ("RSP", "Research & Strategic Partnerships, 620 MCB"),
    ("SALP", "Student Development, 119 SMSU"),
    ("SATT", "Student Affairs Technical Team, C3 NH"),
    ("SBA", "Business Administration, School of, 560 SBA"),
    ("SBA-MIM", "Master of International Management, 540 SBA"),
    ("SBA-STUDENT SERVICES", "Business Administration, School of, Student Services, 240 SBA"),
    ("SCH", "School of Community Health, 450 URBN"),
    ("SCS", "School Computing Support CAT, 82 FAB"),
    ("SEC", "Science and Education Center, 335 UCB"),
    ("SFS-AR", "Non-Credit Solutions, 153 NH"),
    ("SFS-AR", "Student Financial Services - Accounts Receivable, 154 NH"),
    ("SFS-CA", "Student Financial Services - Cashiers, 178 NH"),
    ("SHAC", "Student Health and Counseling, Student Affairs, 200 UCB"),
    ("SMCO", "Smith Center Operations Office, 116 SMSU"),
    ("SMCO-STORE", "University Market, 105 SMSU"),
    ("SMSU", "Conferences & Events"),
    ("SOC", "Sociology Department, 217 CH"),
    ("SP", "Communication Department, 440 UCB"),
    ("SPA", "Sponsored Projects Administration, 210 MCB"),
    ("SPED", "Special Education & Counselor Education, 204 ED"),
    ("SPHR", "Speech & Hearing Sciences, 85 NH"),
    ("SPS", "Student Parent Services, 124 SMSU"),
    ("SRL", "Survey Research Lab, 400 MCB"),
    ("SSS", "Science Support Services, B1 SB1"),
    ("SSW", "Social Work, School of, 670 ASRC"),
    ("SUST", "Center for Sustainable Processes and Practices, MCB"),
    ("SVS", "Student Veteran Services, 401 SMSU"),
    ("SYSC", "Systems Science, 104 HH"),
    ("TA", "Theatre & Film, School of, 127 LH"),
    ("TAPS", "Parking, 145 ASRC"),
    ("TELE", "Telecommunications, 400 UTS"),
    ("TELEFUND", "Telefund, 360 MCB"),
    ("TLC", "The Learning Center,439 SMSU"),
    ("UB", "Upward Bound, 110 KHSE"),
    ("UCOMM", "University Communications, 810 MCB"),
    ("UGenCou", "Univeristy General Counsel, 731 MCB"),
    ("UHO", "University Housing Office, 210 BHB"),
    ("UNST", "University Studies, 117 CH"),
    ("UPA", "Urban & Public Affairs, College of, 750 URBN"),
    ("UPL", "University Place"),
    ("USP", "Urban Studies & Planning, School of, 350 URBN"),
    ("USS", "User Support Services, 18 SMSU"),
    ("VC", "Viking Club, 165 ML"),
    ("VG", "Vanguard, S26 SMSU"),
    ("VP-EM-SA", "Vice President for Enrollment Management and Student Affairs, 345 CH"),
    ("VP-EM-SA", "Student Affairs, Office of, 345 CH"),
    ("WASA", "WASADA, 220 EH"),
    ("WCTR", "Writing Center, 188F CH"),
    ("WHSE", "Shipping & Delivery, 114 USB"),
    ("WLL", "Department of World Languages and Literatures, 491 NH"),
    ("WPC", "World Peace Center, 308T UCB"),
    ("WRC", "Womens Resource Center, Montogmery Basement"),
    ("WSC", "Women, Gender, and Sexuality Studies, 150 XSB"),
    ("XS", "Extended Studies, 1050 MSQ"),
]

def initial_data(apps, schema_editor):
    Department = apps.get_model("MyInfo", "Department")
    Building = apps.get_model("MyInfo", "Building")
    Mailcode = apps.get_model("MyInfo", "Mailcode")

    # Bulk import initial departments.
    Department.objects.bulk_create(Department(name=x) for x in DEPARTMENTS)

    # Bulk import initial buildings.
    Building.objects.bulk_create(Building(code=x[0], name=x[1]) for x in BUILDINGS)

    # Bulk import initial mailcodes.
    Mailcode.objects.bulk_create(Mailcode(code=x[0], description=x[1]) for x in MAILCODES)



class Migration(migrations.Migration):

    dependencies = [
        ('MyInfo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data)
    ]
